import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "tailwindcss/tailwind.css";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "IP address tracker solution",
	description: "frontendmentor.io challange - Generated by create next app",
	creator: "Kraken-afk",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
